### ISSUE TITLE
Attacker can perpetually avoid using updated OfferCut or updated unsuccessfulFee

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#43] opened 2018-11-19 07:12 UTC
### Description

`.updateOffer()` fails to update `offer.offerCut` and `offer.unsuccessfulFee`.

### Scenario

The `Offer` struct records the value of `offerCut` and `unsuccessfulFee` at the time that an offer is made. When a new bidder outbids the original bid, if COO has changed the values of either `offerCut` or `unsuccessfulFee`, the new values are used.

However, `.updateOffer()` fails to update `offerCut` and `unsuccessfulFee`. Every time that a bidder updates their offer, the original `offerCut` and `unsuccessfulFee` are still used, rather than the values of `offerCut` and `unsuccessfulFee` that existed at the time of the offer update. 

If CK updates their fees, users can perpetually avoid the new fees by repeatedly updating their offers by 1 wei every time the offer is about to expire.

### Impact

Medium - every time that CK updates their fees, any user that wishes to use the old fees only needs to continue calling `.updateOffer()` every time their current offers are about to expire. Since `.updateOffer()` does not take a minimum amount of wei to update, users can simply submit a bid of 1 wei.

### Reproduction

(1) CK initializes the value of `offerCut` to 500 (0.5%) and `unsuccessfulFee` to 0.001 ETH.
(2) An Attacker calls `.createOffer()` on a desired token. 
(3) `.createOffer()` saves the offer, storing 0.5% for `offerCut` and 0.001 ETH for `unsuccessfulFee`.
(4) CK updates the value of `offerCut` to 3750 (3.75%) and `unsuccessfulFee` to 0.008 ETH.
(5) Every time that the Attacker's offer is about to expire, they call `.updateOffer()` for 1 wei more than their previous bid.
(6) `Offers.sol` continues to use 0.5% and 0.001 ETH for the offer in perpetuity, never using the updated values of `offerCut` and `unsuccessfulFee`.

### Fix

Add the following two lines to `.updateOffer()`:
```
offer.offerCut = uint16(offerCut);
offer.unsuccessfulFee = uint128(unsuccessfulFee);
```

**Comment by Amandarg** [comment] 2018-11-19 12:37
I think they are aware of this since in the comments it says 
’’’
 /// @notice As the offers are always using the configuration values currently in storage, the updated
    ///  offer may be adhering to configuration values that are different at the time of its original creation.
’’’

**Comment by hwrdtm** [comment] 2018-11-19 22:47
Thanks @michaelKim4736 for your feedback.

Whenever a bidder decides to create an offer, they are agreeing to the current `offerCut` and `unsuccessfulFee` at that time. It is by design that, should this offer ever get updated, it uses the previous values relating to the fees. 

We do our best to inform users well in advance of any changes to the contract configuration values. Should a user wish to have an offer with new configuration values, he/she should either wait for the old offer to expire before creating a new one, or cancel the old offer and create a new one.

This is intended by design. Closing for now.

**Closed by hwrdtm** 2018-11-19 22:47 UTC
